modLoader="javafml"
loaderVersion="[4,)"
license="Microsoft Reciprocal License (Ms-RL)"

[[mods]]
modId="pitagna_mod"
version="1.0.1"
displayName="Pitagna mod"
displayURL="https://modrinth.com/project/pitagna-mod"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Ahomine_"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.pitagna_mod]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.123,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.pitagna_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration